// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Note: This project appears to only be configured for web.
    // If you need to run on other platforms, re-run `flutterfire configure`.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmAJHleCt7uepzO6mj49kLGqQYo8Kw9JI',
    appId: '1:203654547392:web:ccca39d3bd73a335e1aa25',
    messagingSenderId: '203654547392',
    projectId: 'gestao-obras-bf6ff',
    authDomain: 'gestao-obras-bf6ff.firebaseapp.com',
    storageBucket: 'gestao-obras-bf6ff.firebasestorage.app',
    measurementId: 'G-2FGQLNJHK8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmAJHleCt7uepzO6mj49kLGqQYo8Kw9JI',
    appId: '1:203654547392:web:bab756dabd4470bde1aa25',
    messagingSenderId: '203654547392',
    projectId: 'gestao-obras-bf6ff',
    authDomain: 'gestao-obras-bf6ff.firebaseapp.com',
    storageBucket: 'gestao-obras-bf6ff.firebasestorage.app',
    measurementId: 'G-CH4ZG9SNP0',
  );

}